# Generated by Django 5.1.2 on 2024-10-24 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.BooleanField(default=False, help_text='0-inactive, 1-active'),
        ),
    ]
